### ISSUE TITLE
CONTRIBUTING.md with guidelines for changes

### ISSUE THREAD

**Issue by JRHeaton** [stagebloc/CocoaBloc#78]
We ran into an issue once before where a seemingly valid contribution never reached `master` because there were additional housekeeping changes to attend to that weren't outlined clearly. It's the responsible thing to do as an open source library to clarify these things in writing, and will help us hold ourselves accountable for the defined required work when contributing.

Things to outline:
- [ ] How to use `Carthage` to fetch and build dependencies for local development
- [ ] Which styling rules (guide link?) our code conforms to for both ObjC and Swift
- [ ] Steps to make a change. (fork, branch, change, PR)
- [ ] Documentation guidelines (both code and markdown)
- [ ] Which things unit tests are required for (or rather, anything they're _not_ required for, if any)
- [ ] How to verify everything builds and run tests
- [ ] How to do a version bump

**Comment by joshholat** [comment]
:+1: Yes, we need this real bad
